-- AlterTable
ALTER TABLE "collaborators" ALTER COLUMN "create_at" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "update_at" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "points" ALTER COLUMN "lunchTimeStart" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "lunchTimeEnd" SET DATA TYPE TIMESTAMPTZ(6);
